targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            soul: lib/data/local/soul_database.dart
          schema_dir: drift_schemas/
          test_dir: test/drift/
